import * as Yup from 'yup';

export const AlimentacaoNutricaoValidation = Yup.object().shape({
    morar_retomada_mudou_alimentacao: Yup.string().nullable(),
    luta_por_terra: Yup.string().required('Você precisa selecionar se há conflitos por terra'),
    sem_alimentacao_por_conflito_com_terras: Yup.string().nullable(),
    motivo_sem_alimentacao_por_conflito_com_terras: Yup.string().nullable(),
    origem_comida: Yup.string().required('Você precisa preencher a origem das comidas'),
    possui_moradores_menores_de_16: Yup.string().required('Você precisa preencher se há moradores menores de 16 anos'),
    consumiram_sempre_alimentos_da_cultura: Yup.string().required('Você precisa preencher se comeu alimentos da cultura'),
    acao_quando_falta_comida: Yup.array().nullable(),
    morador_faz_horta: Yup.string().required('Você precisa preencher sobre fazer horta'),
    motivo_morador_nao_faz_horta: Yup.array().nullable(),
    alimentos_da_horta: Yup.array().nullable(),
    frutiferas_nas_proximidades: Yup.array().nullable(),
    producao_de_comida_ano_todo: Yup.array().nullable(),
    origem_semente_plantio: Yup.array().nullable(),
    adiciona_veneno_na_plantacao: Yup.string().nullable(),
    dificuldade_com_horta: Yup.string().nullable(),
    lista_dificuldades_com_horta: Yup.array().nullable(),
    finalidade_horta: Yup.string().nullable(),
    animais_de_criacao_alimentacao_ou_venda: Yup.string().required('Você precisa preencher sobre os animais'),
    lista_animais_de_criacao_alimentacao_ou_venda: Yup.string().required('Você precisa'),
    domicilio_possui_agua_para_animais: Yup.string().nullable(),
    domicilio_possui_agua_para_producao_alimentos: Yup.string().required('Você precisa preencher sobre a água para alimentos'),
    precisou_comprar_alimentos_3m: Yup.string().required('Você precisa preencher sobre a necessidade de comprar alimentos'),
    lugar_precisou_comprar_alimentos_3m: Yup.string().nullable(),
    possui_cultivo_plantas_medicinais: Yup.string().nullable(),
    faz_remedios_com_plantas: Yup.string().required('Você precisa preencher sobre a produção de remédios'),
    moradia_possui_fogao: Yup.array().required('Você precisa preencher sobre o fogão'),
    material_utilizado_para_fazer_fogo: Yup.string().required('Você precisa preencher sobre o material para fazer fogo'),
    alimentos_consumidos_dia_anterior: Yup.array().required('Você precisa preencher sobre os alimentos do dia anterior'),
    primeiros_a_se_alimentar: Yup.string().nullable(),
    ultimos_a_se_alimentar: Yup.string().nullable(),

    alimentacao_saudavel_diariamente_30d: Yup.string().required('Você precisa preencher se tiveram alimentos saudáveis diariamente'),
    comida_disponivel_todos_os_dias_30d: Yup.string().required('Você precisa preencher se teve comida todos os dias'),
    dia_sem_alimentos_30d: Yup.string().required('Você precisa preencher sobre os dias sem alimentos'),
    preocupacao_em_conseguir_comida_30d: Yup.string().nullable(),
    alimentacao_do_gosto_30d: Yup.string().nullable(),
    comeu_menos_para_alimentar_os_jovens_30d: Yup.string().nullable(),
    jovens_comeram_menos_do_necessario_30d: Yup.string().nullable(),
    jovens_passaram_algum_dia_sem_alimentos_30d: Yup.string().nullable(),


});