import * as Yup from 'yup';

export const ApoioProtecaoSocialValidation = Yup.object().shape({
    morador_matriculado_na_educacao_basica_publica: Yup.string().required('Você precisa preencher sobre a educação básica'),
    quantidade_morador_matriculado_na_educacao_basica_publica: Yup.number().nullable(),
    criancas_comem_na_escola: Yup.string().required('Você precisa preencher sobre as crianças comerem na escola'),
    escola_inclui_alimentos_da_cultura: Yup.string().required('Você precisa preencher sobre os alimentos culturais na merenda'),
    morador_recebe_ajuda_financeira: Yup.string().required('Você precisa preencher sobre ajuda financeira'),
    quantidade_cesta_de_alimentos_3m: Yup.number().nullable(),
    origem_cesta_de_alimentos_3m: Yup.array().nullable(),
    alimentos_deveriam_estar_na_cesta_e_nao_estao: Yup.array().nullable(),
    alimentos_que_nao_deveriam_estar_na_cesta: Yup.array().nullable(),
    descricao_adicionar_outro: Yup.string().nullable(),
    descricao_remover_outro: Yup.string().nullable(),
    motivo_nao_recebe_cesta_de_alimentos: Yup.string().nullable(),
    quem_pega_dinheiro_bolsa_familia: Yup.string().nullable(),
    auxilio_emergencial_na_pandemia: Yup.string().required('Você precisa preencher sobre auxílio emergencial na pandemia'),
    quantidade_vezes_auxilio_emergencial_na_pandemia: Yup.string().nullable(),
    ajuda_estado_prefeitura_outros_3m: Yup.string().required('Você precisa preencher sobre ajuda do estado'),
    itens_recebidos_ajuda_estado_prefeitura_outros_3m: Yup.string().nullable(),
    vergonha_constrangimento_para_conseguir_alimentos_3m: Yup.string().required('Você precisa preencher sobre constrangimento para conseguir alimento'),

    bolsa_familia_auxilio_brasil: Yup.string().nullable(),
    bpc: Yup.string().nullable(),
    beneficio_deficientes_ou_idosos: Yup.string().nullable(),
    auxilio_maternidade: Yup.string().nullable(),
    auxilio_doenca: Yup.string().nullable(),
    auxilio_reclusao: Yup.string().nullable(),
    aposentadoria: Yup.string().nullable(),
    pensao_morte_conjuge: Yup.string().nullable(),
    pronaf: Yup.string().nullable(),
    auxilio_estadual_ou_municipal: Yup.string().nullable(),
    cesta_de_alimentos: Yup.string().nullable(),
});