import * as Yup from 'yup';

export const SaudeDoencaValidation = Yup.object().shape({
    tomou_vacina_covid: Yup.string().required('Você precisa'),
    motivo_nao_tomar_vacina_covid: Yup.string().required('Você precisa'),
    condicao_de_saude: Yup.string().required('Você precisa'),
    tekoha_mudou_condicao_de_saude: Yup.string().nullable(),
    morador_exposto_veneno_lavoura: Yup.string().required('Você precisa'),
    doencas_contato_veneno_lavoura: Yup.string().nullable(),
    motivo_doencas_contato_veneno_lavoura: Yup.string().nullable(),
    acidentes: Yup.string().required('Você precisa'),
    acidentes_ocorridos: Yup.string().nullable(),
    ocorrencia_de_ameacas: Yup.string().required('Você precisa'),
    ocorrencia_violencia_fisica: Yup.string().required('Você precisa'),
    local_ocorrencia_violencia_fisica: Yup.array().nullable(),
    lista_tratamentos: Yup.array().required('Você precisa'),
    tratamento_com_paje_ou_similar: Yup.string().required('Você precisa'),
    tratamento_igreja: Yup.string().required('Você precisa'),
    medicacao_uso_continuo: Yup.string().required('Você precisa'),
    doenca_medicacao_uso_continuo: Yup.array().nullable(),
    primeiro_recurso_ao_notar_doenca: Yup.string().required('Você precisa'),
    morador_internado: Yup.string().required('Você precisa'),
    morador_problemas_bebidas_alcoolicas: Yup.string().required('Você precisa'),
    morador_problemas_uso_drogas: Yup.string().required('Você precisa'),
    familiar_morte_covid: Yup.string().nullable(),
    familiar_morte_covid_contribuia_renda_familiar: Yup.string().nullable(),
    familiares_morte_outras_causas: Yup.string().nullable(),
    motivo_familiares_morte_outras_causas: Yup.string().nullable(),
    familiares_morte_outras_causas_contribuia_renda_familiar: Yup.string().nullable(),
});