export default interface ICreateViolenceDTO {
  ofensa_humilhacao_ridicularizacao: string;
  ofensa_humilhacao_ridicularizacao_local?: string;
  ofensa_humilhacao_ridicularizacao_local_outro?: string;
  gritou_xingou: string;
  gritou_xingou_local?: string;
  gritou_xingou_local_outro?: string;
  ameacas_ofensas_exposicao_por_redes_sociais: string;
  ameacas_ofensas_exposicao_por_redes_sociais_local?: string;
  ameacas_ofensas_exposicao_por_redes_sociais_local_outro?: string;
  ameacas_verbais: string;
  ameacas_verbais_local?: string;
  ameacas_verbais_local_outro?: string;
  destruiu_pertences_de_proposito: string;
  destruiu_pertences_de_proposito_local?: string;
  destruiu_pertences_de_proposito_local_outro?: string;
  tapa_bofetada: string;
  tapa_bofetada_local?: string;
  tapa_bofetada_local_outro?: string;
  empurrou_segurou_ou_jogou_algo_com_intencao_de_machucar: string;
  empurrou_segurou_ou_jogou_algo_com_intencao_de_machucar_local?: string;
  empurrou_segurou_ou_jogou_algo_com_intencao_de_machucar_local_outro?: string;
  soco_chute_ou_arrastou_pelo_cabelo: string;
  soco_chute_ou_arrastou_pelo_cabelo_local?: string;
  soco_chute_ou_arrastou_pelo_cabelo_local_outro?: string;
  tentou_ou_estrangulou_asfixiou_ou_queimou: string;
  tentou_ou_estrangulou_asfixiou_ou_queimou_local?: string;
  tentou_ou_estrangulou_asfixiou_ou_queimou_local_outro?: string;
  ameacou_ou_feriu_com_faca_arma_ou_outros_objetos: string;
  ameacou_ou_feriu_com_faca_arma_ou_outros_objetos_local?: string;
  ameacou_ou_feriu_com_faca_arma_ou_outros_objetos_local_outro?: string;
  tocou_manipulou_beijou_expos_corpo_contra_vontade: string;
  tocou_manipulou_beijou_expos_corpo_contra_vontade_local?: string;
  tocou_manipulou_beijou_expos_corpo_contra_vontade_local_outro?: string;
  ameacou_forcou_relacoes_ou_atos_sexuais_contra_vontade: string;
  ameacou_forcou_relacoes_ou_atos_sexuais_contra_vontade_local?: string;
  ameacou_forcou_relacoes_ou_atos_sexuais_contra_vontade_local_outro?: string;
}

